#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate

if [ "${DJANGO_DEBUG_MODE:-0}" = "1" ]; then
    echo "Starting Django in debug mode - waiting for debugger to attach..."
    exec python -m debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver_plus 0.0.0.0:8000
else
    echo "Starting Django in normal mode..."
    exec python manage.py runserver_plus 0.0.0.0:8000
fi
