services:
  docs:
    image: awe_system_ui_local_docs
    container_name: awe_system_ui_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./awe_system_ui:/app/awe_system_ui:z
    ports:
      - '9000:9000'
    command: /start-docs
