# Generated by Django 5.0.10 on 2024-12-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
