# Generated by Django 5.0.10 on 2024-12-22 03:19

import awe_system_ui.llm_caller.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0004_llmconfig_llmmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apirequest',
            old_name='prompt',
            new_name='essay',
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='prompt_template',
            field=models.TextField(default='Please help evalute the following essay between 0 - 5:\n{essay}', help_text="Use '{essay}' (without the quote) as placeholder for user input", validators=[awe_system_ui.llm_caller.models.validate_user_prompt_template]),
        ),
    ]
