# Generated by Django 5.0.10 on 2025-01-02 07:08

import awe_system_ui.llm_caller.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0005_rename_prompt_apirequest_essay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='prompt_template',
            field=models.TextField(default='Evaluate the following essay and score it between 0 and 5:\n{essay}', help_text="Use '{essay}' (without the quote) as placeholder for user input", validators=[awe_system_ui.llm_caller.models.validate_user_prompt_template]),
        ),
    ]
