# Generated by Django 5.0.10 on 2025-01-18 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0007_remove_llmconfig_prompt_template_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llmmodel',
            options={'get_latest_by': 'created_at', 'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='apirequest',
            name='model',
            field=models.ForeignKey(default=1, help_text='The LLM model used for this request', on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='llm_caller.llmmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='is_default',
            field=models.BooleanField(default=False, help_text='This model will be pre-selected in the UI'),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='order',
            field=models.IntegerField(default=10, help_text='Order of the model in the UI (smaller number comes first)'),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only active models will be listed in the UI'),
        ),
    ]
