# Generated by Django 5.0.10 on 2025-01-18 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0008_alter_llmmodel_options_apirequest_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotaconfig',
            name='model',
            field=models.OneToOneField(default=1, help_text='The LLM model this quota applies to', on_delete=django.db.models.deletion.CASCADE, related_name='quota_config', to='llm_caller.llmmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotaconfig',
            name='daily_limit',
            field=models.IntegerField(default=10, help_text='Maximum number of requests per day for this model'),
        ),
    ]
