# Generated by Django 5.0.10 on 2025-01-24 15:09

import awe_system_ui.llm_caller.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0009_quotaconfig_model_alter_quotaconfig_daily_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="OpenAI API Key (starts with 'sk-')", max_length=255)),
                ('name', models.CharField(help_text="A name to identify this key (e.g., 'Primary Key', 'Backup Key')", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Only active keys will be used')),
                ('order', models.IntegerField(default=10, help_text='Keys with lower order values will be used first', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OpenAI API Key',
                'verbose_name_plural': 'OpenAI API Keys',
                'ordering': ['order'],
            },
        ),
    ]
