# Generated by Django 5.0.10 on 2025-01-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0010_openaikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='system_prompt',
            field=models.TextField(default='You are an essay scoring assistant that always outputs JSON that matches this schema:\nclass Response\n    score: float\n    reasoning: str\n\nRequirements:\n- Score must be a float between 0 and 10\n- Reasoning must explain the rationale for the score\n- Output must be a valid JSON object with \'score\' and \'reasoning\' fields\n- Example valid response: {"score": 8.5, "reasoning": "The essay demonstrates strong critical thinking and clear organization..."}\n\nInvalid responses:\n- {"score": "8.5"}  # score as string is invalid\n- {"score": 11}     # score > 10 is invalid\n- {"grade": 8.5}    # wrong field name', help_text='The system prompt instructs the model to generate JSON format.'),
        ),
    ]
