# Generated by Django 5.0.10 on 2025-02-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0011_apirequest_reasoning_alter_llmconfig_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag - True means this request is deleted'),
        ),
    ]
