# Generated by Django 5.0.10 on 2025-02-02 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0012_apirequest_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llmconfig',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one config can be active per model'),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='target_llm_model',
            field=models.ForeignKey(default=1, help_text='The LLM model this configuration applies to', on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='llm_caller.llmmodel'),
            preserve_default=False,
        ),
    ]
