# Generated by Django 5.0.10 on 2025-02-04 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0013_alter_llmconfig_options_llmconfig_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='llm_type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('third_party', 'Third Party')], default='openai', help_text='The type of LLM service to use', max_length=20),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='url',
            field=models.URLField(blank=True, help_text='URL for third-party LLM service (leave empty for OpenAI)', max_length=500, validators=[django.core.validators.URLValidator()]),
        ),
    ]
