# Generated by Django 5.0.10 on 2025-02-06 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0014_llmmodel_llm_type_llmmodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmmodel',
            name='url',
            field=models.URLField(blank=True, help_text='URL for third-party LLM service (e.g., http://host.docker.internal:8080/v1). Leave empty for OpenAI.', max_length=500, validators=[django.core.validators.URLValidator()]),
        ),
    ]
