# Generated by Django 5.0.10 on 2025-02-06 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0015_alter_llmmodel_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openaikey',
            options={'ordering': ['created_at'], 'verbose_name': 'API Key', 'verbose_name_plural': 'API Keys'},
        ),
        migrations.RemoveField(
            model_name='openaikey',
            name='name',
        ),
        migrations.RemoveField(
            model_name='openaikey',
            name='order',
        ),
        migrations.AddField(
            model_name='openaikey',
            name='model',
            field=models.ForeignKey(default=1, help_text='The LLM model this key is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='llm_caller.llmmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='openaikey',
            name='key',
            field=models.CharField(help_text="API Key (e.g., OpenAI starts with 'sk-')", max_length=255),
        ),
    ]
