# Generated by Django 5.0.10 on 2025-02-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0016_alter_openaikey_options_remove_openaikey_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpenAIKey',
            new_name='APIKey',
        ),
    ]
