# Generated by Django 5.0.10 on 2025-02-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0018_batchprocessing_batchitem_batchprocessingquota'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocessing',
            name='task_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
