# Generated by Django 5.0.10 on 2025-02-08 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0019_batchprocessing_task_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchprocessing',
            options={'ordering': ['-created_at'], 'permissions': [('can_manage_limited_batchprocessings', 'Can manage batch processing requests with limited visibility')], 'verbose_name_plural': 'Batch processing requests'},
        ),
        migrations.RemoveField(
            model_name='batchprocessing',
            name='user',
        ),
        migrations.AddField(
            model_name='batchprocessing',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
