# Generated by Django 5.0.10 on 2025-02-08 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0020_alter_batchprocessing_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apirequest',
            options={'ordering': ['-created_at'], 'permissions': [('can_manage_limited_apirequests', 'Can manage API requests with limited visibility')]},
        ),
        migrations.RemoveField(
            model_name='apirequest',
            name='user',
        ),
        migrations.AddField(
            model_name='apirequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
