# Generated by Django 5.0.10 on 2025-02-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0021_alter_apirequest_options_remove_apirequest_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchprocessing',
            name='output_file',
            field=models.FileField(blank=True, help_text='Excel file containing the results of the batch processing', null=True, upload_to='batch_outputs/%Y/%m/%d/'),
        ),
    ]
