# Generated by Django 5.0.10 on 2025-02-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0022_alter_batchprocessing_output_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='error_details',
            field=models.TextField(blank=True, default='', help_text='Error details to diagnose the error.'),
        ),
        migrations.AddField(
            model_name='batchitem',
            name='error_details',
            field=models.TextField(blank=True, default='', help_text='Error details to diagnose the error.'),
        ),
        migrations.AlterField(
            model_name='apirequest',
            name='error',
            field=models.TextField(blank=True, default='', help_text='Error message that displays to the user.'),
        ),
        migrations.AlterField(
            model_name='batchitem',
            name='error',
            field=models.TextField(blank=True, default='', help_text='Error message that displays to the user.'),
        ),
        migrations.AlterField(
            model_name='batchitem',
            name='reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='batchitem',
            name='result',
            field=models.TextField(blank=True, default=''),
        ),
    ]
