# Generated by Django 5.0.10 on 2025-02-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0024_apirequest_ended_at_apirequest_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocessing',
            name='error',
            field=models.TextField(blank=True, default='', help_text='Error message that displays to the user.'),
        ),
        migrations.AddField(
            model_name='batchprocessing',
            name='error_details',
            field=models.TextField(blank=True, default='', help_text='Error details to diagnose the error.'),
        ),
    ]
