# Generated by Django 5.0.10 on 2025-02-09 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0025_batchprocessing_error_batchprocessing_error_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchprocessing',
            name='input_file',
        ),
    ]
