# Generated by Django 5.0.10 on 2025-02-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0026_remove_batchprocessing_input_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchprocessing',
            name='output_file',
        ),
    ]
