# Generated by Django 5.0.10 on 2025-02-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0027_remove_batchprocessing_output_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ABORTED', 'Aborted')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='batchprocessing',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ABORTED', 'Aborted')], default='PENDING', max_length=20),
        ),
    ]
