# Generated by Django 5.0.10 on 2025-02-15 07:30

import awe_system_ui.llm_caller.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0028_alter_batchitem_status_alter_batchprocessing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='essay_topic',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='batchitem',
            name='essay_topic',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='batchprocessing',
            name='essay_topic_field_name',
            field=models.CharField(default='Essay Topic', help_text='Column name containing the essay topics in the Excel file', max_length=50),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='user_prompt_template',
            field=models.TextField(default='Please evaluate the following essay on the topic of "{essay_topic}":\n\n{essay}', help_text="Use '{essay}' (without the quote) as placeholder for user input<br>Use '{essay_topic}' (without the quote) as placeholder for the essay topic", validators=[awe_system_ui.llm_caller.models.validate_user_prompt_template]),
        ),
    ]
