# Generated by Django 5.0.10 on 2025-02-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0029_apirequest_essay_topic_batchitem_essay_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ABORTED', 'Aborted')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='apirequest',
            name='task_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
