# Generated by Django 5.0.10 on 2025-02-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0030_alter_apirequest_status_alter_apirequest_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='user_prompt',
            field=models.TextField(blank=True, default='', help_text='The actual prompt sent to the LLM'),
        ),
        migrations.AddField(
            model_name='batchitem',
            name='user_prompt',
            field=models.TextField(blank=True, default='', help_text='The actual prompt sent to the LLM'),
        ),
    ]
