# Generated by Django 5.0.10 on 2026-06-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0031_apirequest_user_prompt_batchitem_user_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='lora_id',
            field=models.PositiveIntegerField(default=0, help_text='Adapter index from GET /lora-adapters on the server. Usually 0 with one adapter.'),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='lora_scale',
            field=models.FloatField(default=1.0, help_text='Scale applied when use_lora is on (1.0 = full).'),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='use_lora',
            field=models.BooleanField(default=False, help_text='Activates the LoRA adapter for requests to this model on a shared llama.cpp instance.'),
        ),
    ]
