# Generated by Django 5.0.10 on 2026-06-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0032_llmmodel_lora_id_llmmodel_lora_scale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='available_to_anonymous',
            field=models.BooleanField(default=False, help_text='Allow logged-out users to use this model (e.g. the public TOEFL model).'),
        ),
    ]
