# Generated by Django 5.0.10 on 2026-06-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0033_llmmodel_available_to_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='feedback_language',
            field=models.CharField(default='English', help_text='Language the LLM should write its reasoning in.', max_length=32),
        ),
    ]
