#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Create staticfiles directory if it doesn't exist and ensure proper permissions
mkdir -p /app/staticfiles
python /app/manage.py collectstatic --noinput

exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
