# Generated by Django 5.0.10 on 2025-01-22 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['course_id'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.ForeignKey(blank=True, help_text='The course this student belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.course'),
        ),
    ]
