# Generated by Django 5.0.10 on 2025-02-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options_user_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_courses',
            field=models.ManyToManyField(blank=True, help_text='Courses that this user manages.', related_name='managers', to='users.course'),
        ),
    ]
